#server:
#  port: 8082

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.yc.fresh.service.entity
  executor-type: reuse


  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    defaultStatementTimeout: 15000
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8

swagger: true

redisson:
  client-name: FreshRedisCli
  host: 39.99.135.185
  port: 6379
  pwd: w8y0E,Xm





